---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: docker
      #ansible_host: 172.17.0.3 #02bfc65ac471

vector:
  hosts:
    vector-01:
      ansible_connection: docker
      #ansible_host: 172.17.0.2 #6e91fdf165f7